baseURL: https://abheek-dutta.netlify.app/
languageCode: en-us
title: Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Abheek
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: adutta.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +447634450961
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: An LBS student
        title: About me
        url: blogs/About me
      - image: pic02.jpg
        subtitle: Best thing I've seen in my life
        title: My Favourite Holiday Destination
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: The best pass-time
        title: Sports
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Heritage
        title: Nationality and Ancestry
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Anything fast-paced
        title: Music
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Data Analysis 
        title: Some R data
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: My name is Abheek and I read the Masters in Financial Analysis at LBS. I am originally from the UK and like to play sports, travel and listen to music in my spare time. Feel free to open any tabs to get a clearer picture on myself.
    title: A short Introduction
    url: blogs
